#ifndef MARIO_CUSTOM_ANIMS_H_INCLUDED
#define MARIO_CUSTOM_ANIMS_H_INCLUDED

extern int MARIO_ANIM_CUSTOM_TEST;
extern int MARIO_ANIM_CUSTOM_CLOSE_CAR_DOOR_LEFT;
extern int MARIO_ANIM_CUSTOM_CLOSE_CAR_DOOR_RIGHT;
extern int MARIO_ANIM_CUSTOM_PICKUP_SLOW;
extern int MARIO_ANIM_CUSTOM_PUTDOWN_SLOW;
extern int MARIO_ANIM_CUSTOM_CAR_LOCKED;
extern int MARIO_ANIM_CUSTOM_EAT;
extern int MARIO_ANIM_CUSTOM_VOMIT;
extern int MARIO_ANIM_CUSTOM_CRIB_SWITCH;
extern int MARIO_ANIM_CUSTOM_FACEPALM;
extern int MARIO_ANIM_CUSTOM_LAUGH01;

void marioInitCustomAnims();

#endif // MARIO_CUSTOM_ANIMS_H_INCLUDED
